apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-hello-app.fullname" . }}
  labels:
    {{- include "kube-hello-app.labels" . | nindent 4 }}
# immutable: true
data:
  SERVER_PORT: {{ .Values.service.targetPort | quote }}
