{{- $secretNamePrefix := (include "kube-hello-app.fullname" .) -}}
{{- with $mongo := .Values.components.mongo }}
  {{- if $mongo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s.%s" $secretNamePrefix $mongo.secretName }}
type: Opaque
immutable: {{ $mongo.immutable }}
data:
  HELLO_APP_CREDENTIALS_MONGO_USERNAME: {{ $mongo.username | b64enc | quote }}
  HELLO_APP_CREDENTIALS_MONGO_PASSWORD: {{ $mongo.password | b64enc | quote }}
  {{- end }}
{{- end }}


