
name: Publish on DockerHub

on:
  release:
    types:
      - created
    
jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name:  Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          server-id: github

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
  publish_docker_images:
    needs: build
    runs-on: ubuntu-18.04
    env:
      # Use docker.io for Docker Hub if empty
      REGISTRY: docker.io # ghcr.io
      # github.repository as <account>/<repo>
      IMAGE_NAME: ${{ github.repository }}
      # IMAGE_NAME_EXT: ${{ env.REGISTRY }}/${{ github.repository }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Get image version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        
      - name: Check version
        run: |
          echo ${{ steps.vars.outputs.tag }}
          echo ${{ github.event.release.tag_name }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      # - name: Extract Docker metadata
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          IMAGE_NAME_EXT: ${{ env.REGISTRY }}/${{ github.repository }}
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=${{ env.IMAGE_NAME_EXT }}:latest
          cache-to: type=inline
          tags: ${{ env.IMAGE_NAME_EXT }}:latest, ${{ env.IMAGE_NAME_EXT }}:${{ github.event.release.tag_name }}
          
        
   
