name: Release with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name:  Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          server-id: github

      - name: Configure Git user
        run: |
          git config user.email "alessandro.venditti1995@gmail.com"
          git config user.name "Alessandro Venditti"

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish JAR
        run: mvn -B release:prepare -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
